import json

import pytest

from coursekit import agents
from coursekit.cli import main
from coursekit.project import find_project

SKILLS = ("instructional-design", "content-writing", "content-review", "creator-assembly", "media-production", "delivery")


@pytest.fixture
def project(tmp_path, monkeypatch):
    for key in ("COURSEKIT_PROJECT", "WRITER_AGENT", "WRITER_MODEL", "REVIEWER_AGENT", "REVIEWER_MODEL"):
        monkeypatch.delenv(key, raising=False)
    root = tmp_path / "demo"
    assert main(["init", str(root), "--yes", "--no-git", "--client", "ACME"]) == 0
    text = (root / "project.yaml").read_text(encoding="utf-8")
    (root / "project.yaml").write_text(text.replace('mcp_url: ""', 'mcp_url: "https://acme.example/mcp"'), encoding="utf-8")
    monkeypatch.chdir(root)
    return root


def generated(root):
    return [p for p in root.rglob("*.md") if agents.MARKER in p.read_text(encoding="utf-8")]


def test_init_generates_every_tool(project):
    for name in SKILLS:
        for base in (".claude/skills", ".opencode/skill", ".coursekit/agents/skills"):
            assert (project / base / name / "SKILL.md").exists(), (base, name)
    assert (project / ".claude/commands/write-unit.md").exists()
    assert (project / ".opencode/agent/writer.md").exists()
    assert (project / ".coursekit/docs/content-format.md").exists()


def test_no_token_is_left_unrendered(project):
    assert main(["agents"]) == 0
    files = generated(project)
    assert len(files) > 40
    for path in files:
        text = path.read_text(encoding="utf-8")
        assert "{{" not in text, path
        if path.name == "SKILL.md":
            assert text.startswith("---\nname: "), path  # frontmatter stays first


def test_values_come_from_the_project(project):
    skill = (project / ".claude/skills/instructional-design/SKILL.md").read_text(encoding="utf-8")
    assert "palabrasPorHora: 5000" in skill
    assert '"Introducción y objetivos"' in skill
    rules = project / "config" / "rules.yaml"
    rules.write_text("pages_per_hour: 8\n", encoding="utf-8")
    assert main(["agents"]) == 0
    skill = (project / ".claude/skills/instructional-design/SKILL.md").read_text(encoding="utf-8")
    assert "palabrasPorHora: 4000" in skill


def test_writer_model_from_env(project, monkeypatch):
    monkeypatch.setenv("WRITER_AGENT", "opencode")
    monkeypatch.setenv("WRITER_MODEL", "acme/model-x")
    assert main(["agents"]) == 0
    assert "model: acme/model-x" in (project / ".opencode/agent/writer.md").read_text(encoding="utf-8")
    assert "model:" not in (project / ".opencode/agent/reviewer.md").read_text(encoding="utf-8")


def test_project_override_wins_and_extra_skill(project):
    (project / ".agents/commands").mkdir(parents=True)
    (project / ".agents/commands/write-unit.md").write_text("---\ndescription: ours\n---\n\nOur {{client}} rules.\n", encoding="utf-8")
    (project / ".agents/skills/house-style").mkdir(parents=True)
    skill = "---\nname: house-style\ndescription: x\n---\n\nStyle.\n"
    (project / ".agents/skills/house-style/SKILL.md").write_text(skill, encoding="utf-8")
    (project / ".agents/skills/house-style/example.md").write_text("example\n", encoding="utf-8")
    assert main(["agents"]) == 0
    assert "Our ACME rules." in (project / ".claude/commands/write-unit.md").read_text(encoding="utf-8")
    assert (project / ".opencode/skill/house-style/SKILL.md").exists()
    assert (project / ".claude/skills/house-style/example.md").read_text(encoding="utf-8") == "example\n"
    # removing the override skill removes its generated copies
    import shutil

    shutil.rmtree(project / ".agents/skills/house-style")
    assert main(["agents"]) == 0
    assert not (project / ".claude/skills/house-style").exists()


def test_hand_written_files_are_kept(project, capsys):
    mine = project / ".claude/commands/mine.md"
    mine.write_text("my own command\n", encoding="utf-8")
    edited = project / ".claude/commands/assemble.md"
    edited.write_text("edited by hand, no marker\n", encoding="utf-8")
    capsys.readouterr()
    assert main(["agents"]) == 0
    assert mine.read_text(encoding="utf-8") == "my own command\n"
    assert edited.read_text(encoding="utf-8") == "edited by hand, no marker\n"
    assert "kept (not generated by coursekit): .claude/commands/assemble.md" in capsys.readouterr().out


def test_configs_are_merged(project):
    (project / ".mcp.json").write_text(json.dumps({"mcpServers": {"other": {"type": "http", "url": "https://x"}}}), encoding="utf-8")
    (project / ".claude/settings.json").write_text(json.dumps({"permissions": {"deny": ["Bash(rm:*)"]}, "model": "x"}), encoding="utf-8")
    (project / "opencode.json").write_text(json.dumps({"model": "acme/m", "instructions": ["docs/house.md"]}), encoding="utf-8")
    assert main(["agents"]) == 0
    mcp = json.loads((project / ".mcp.json").read_text(encoding="utf-8"))
    assert set(mcp["mcpServers"]) == {"other", "slxd-creator"}
    settings = json.loads((project / ".claude/settings.json").read_text(encoding="utf-8"))
    assert settings["model"] == "x"
    assert settings["permissions"]["deny"] == ["Bash(rm:*)", *agents.DENY_CLAUDE]
    oc = json.loads((project / "opencode.json").read_text(encoding="utf-8"))
    assert oc["model"] == "acme/m"
    assert oc["instructions"] == ["docs/house.md", "AGENTS.md", ".coursekit/docs/content-format.md"]
    assert oc["permission"]["bash"]["*coursekit approve*"] == "deny"
    assert oc["mcp"]["slxd-creator"]["url"] == "https://acme.example/mcp"
    # running again changes nothing
    before = {p: p.read_text(encoding="utf-8") for p in (project / ".mcp.json", project / "opencode.json")}
    assert main(["agents"]) == 0
    assert before == {p: p.read_text(encoding="utf-8") for p in before}


def test_codex_config_by_hand_is_kept(project):
    codex = project / ".codex/config.toml"
    codex.parent.mkdir(exist_ok=True)
    codex.write_text("[mcp_servers.mine]\nurl = \"https://mine\"\n", encoding="utf-8")
    assert main(["agents"]) == 0
    assert codex.read_text(encoding="utf-8") == "[mcp_servers.mine]\nurl = \"https://mine\"\n"


def test_unknown_token_fails(project, capsys):
    (project / ".agents/commands").mkdir(parents=True)
    (project / ".agents/commands/bad.md").write_text("Uses {{nope}}.\n", encoding="utf-8")
    capsys.readouterr()
    assert main(["agents"]) == 1
    assert "unknown token {{nope}}" in capsys.readouterr().err


def test_english_project(tmp_path, monkeypatch):
    monkeypatch.delenv("COURSEKIT_PROJECT", raising=False)
    root = tmp_path / "en"
    assert main(["init", str(root), "--yes", "--no-git", "--language", "en"]) == 0
    fmt = (root / ".coursekit/docs/content-format.md").read_text(encoding="utf-8")
    assert "## Section 1 — Introduction and objectives" in fmt
    assert "MEDIA ASSET" in fmt
    assert 'address the learner as "you"' in (root / ".claude/skills/content-writing/SKILL.md").read_text(encoding="utf-8")
    assert find_project(root).root == root
