"""`coursekit agents`: render skills, commands, agents and docs for Claude Code, opencode and Codex.

One source: the package files (coursekit/agentkit/) plus the project overrides in `.agents/`
(same layout: `skills/<name>/SKILL.md`, `commands/<name>.md`, `agents/<name>.md`; a project file
replaces the package file of the same name). Every file is rendered with the project values
(`{{name}}` tokens, `{{> partial}}` includes) and written as a copy where each tool reads it:

    .claude/skills/<name>/SKILL.md    .claude/commands/<name>.md
    .opencode/skill/<name>/SKILL.md   .opencode/command/<name>.md   .opencode/agent/<name>.md
    .coursekit/agents/...             (Codex and any other tool: listed in AGENTS.md)
    .coursekit/docs/...               (content format, slxd reference)

and the tool configuration is merged (never replaced) into `.mcp.json`, `opencode.json`,
`.claude/settings.json` and `.codex/config.toml`: the slxd MCP server, and agents denied to run
`coursekit approve` and `git push`. Only files coursekit generated (they carry a marker) are
overwritten or removed.
"""

from __future__ import annotations

import json
import os
import re
import shutil
from dataclasses import dataclass, field
from importlib import resources
from pathlib import Path

from coursekit import config, lang
from coursekit import course as coursemod
from coursekit.project import Project

MARKER = "generated by coursekit agents"
KINDS = ("skills", "commands", "agents", "docs")
TOOLS = ("claude", "opencode", "codex")
ROLES = ("design", "writer", "reviewer", "media", "assembly")
DENY_CLAUDE = ["Bash(coursekit approve:*)", "Bash(git push:*)"]
DENY_OPENCODE = {"*coursekit approve*": "deny", "git push*": "deny"}

LANGUAGE_NAMES = {"es": "Spanish (Spain)", "en": "English"}
ADDRESS_RULES = {
    "tu": "address the learner as «tú»",
    "usted": "address the learner as «usted»",
    "you": 'address the learner as "you"',
}

TOKEN = re.compile(r"\{\{\s*([a-z_][a-z0-9_]*)\s*\}\}")
PARTIAL = re.compile(r"\{\{>\s*([a-z0-9_-]+)\s*\}\}")


class RenderError(Exception):
    pass


@dataclass
class Report:
    written: list[str] = field(default_factory=list)
    unchanged: int = 0
    removed: list[str] = field(default_factory=list)
    kept: list[str] = field(default_factory=list)
    configs: list[str] = field(default_factory=list)


def role(name: str) -> tuple[str, str]:
    """(tool, model) of a role from the environment (.env): <ROLE>_AGENT / <ROLE>_MODEL."""
    key = name.upper()
    tool = (os.environ.get(f"{key}_AGENT") or "claude").strip().lower()
    return tool, (os.environ.get(f"{key}_MODEL") or "").strip()


def context(project: Project) -> dict[str, str]:
    data = config.project_data(project)
    content_language = str(data.get("content_language") or "es")
    ui_language = str(data.get("ui_language") or content_language)
    tokens = lang.tokens(content_language)
    rules = coursemod.rules(project=project)
    content = rules["content"]
    design = rules.get("design") or {}
    address = str(data.get("address") or ("you" if content_language == "en" else "tu"))
    slxd = (data.get("platform") or {}).get("slxd") or {}
    fields = tokens["placeholder_fields"]
    return {
        "project_name": str(data.get("name") or project.root.name),
        "client": str(data.get("client") or ""),
        "tone": str(data.get("tone") or "the one in course.yaml"),
        "language_name": LANGUAGE_NAMES.get(content_language, content_language),
        "ui_language_name": LANGUAGE_NAMES.get(ui_language, ui_language),
        "address_rule": ADDRESS_RULES.get(address, f"address the learner as «{address}»"),
        "backend": str((data.get("assembly") or {}).get("backend") or "creator"),
        "mcp_name": str(slxd.get("mcp_name") or "slxd-creator"),
        "t_section": tokens["section"],
        "t_objective": tokens["objective"],
        "t_placeholder": tokens["placeholder"],
        "t_assessment": tokens["assessment_activity"],
        "t_intro_title": tokens["intro_title"],
        "t_summary_title": tokens["summary_title"],
        "t_unit": tokens["unit"],
        "t_question_key": tokens["question_objective_key"],
        "placeholder_field_lines": "\n".join(f"> **{f}:** …" for f in fields),
        "pages_per_hour": str(rules["pages_per_hour"]),
        "words_per_page": str(rules["words_per_page"]),
        "words_per_hour": str(rules["pages_per_hour"] * rules["words_per_page"]),
        "word_margin_pct": f"{round(float(content.get('word_margin', 0)) * 100):g}",
        "questions_per_objective": str(content["questions_per_objective"]),
        "placeholders_per_hour": f"{content['placeholders_per_hour']:g}",
        "min_placeholder_types": str(content["min_placeholder_types"]),
        "placeholder_types": ", ".join(f"`{t}`" for t in content["placeholder_types"]),
        "interactive_per_hour": f"{content['interactive_per_hour']:g}",
        "min_interactive_per_content_section": str(content["min_interactive_per_content_section"]),
        "allowed_symbols": " ".join(content["allowed_symbols"]),
        "competencies_per_course": str(design.get("competencies_per_course", "2–4")),
        "objectives_per_unit": str(design.get("objectives_per_unit", "2–4")),
        "intro_summary_hours": str(design.get("intro_summary_hours", "0.2–0.3")),
    }


def render(text: str, values: dict[str, str], partials: dict[str, str], where: str = "") -> str:
    def include(m: re.Match) -> str:
        name = m.group(1)
        if name not in partials:
            raise RenderError(f"{where}: unknown partial {{{{> {name}}}}}")
        return partials[name].strip()

    text = PARTIAL.sub(include, text)

    def token(m: re.Match) -> str:
        name = m.group(1)
        if name not in values:
            raise RenderError(f"{where}: unknown token {{{{{name}}}}}")
        return values[name]

    return TOKEN.sub(token, text)


def _package_dir() -> Path:
    return Path(str(resources.files("coursekit.agentkit")))


def collect(project: Project) -> tuple[dict[str, dict[str, Path]], dict[str, str]]:
    """Source files per kind ({name: path}), project overrides winning; and the partials."""
    roots = [_package_dir(), project.root / ".agents"]
    found: dict[str, dict[str, Path]] = {k: {} for k in KINDS}
    partials: dict[str, str] = {}
    for root in roots:
        for kind in KINDS:
            folder = root / kind
            if not folder.is_dir():
                continue
            for entry in sorted(folder.iterdir()):
                if entry.name.startswith(".") or entry.name == "__init__.py" or entry.name == "__pycache__":
                    continue
                if entry.name.startswith("_") and entry.suffix == ".md":
                    partials[entry.stem] = entry.read_text(encoding="utf-8")
                    continue
                if kind == "skills" and entry.is_dir() and (entry / "SKILL.md").exists():
                    found[kind][entry.name] = entry
                elif kind != "skills" and entry.suffix == ".md":
                    found[kind][entry.stem] = entry
    return found, partials


def _mark(text: str, source: str) -> str:
    note = f"<!-- {MARKER}; {source} -->"
    if text.startswith("---"):
        end = text.index("---", 3) + 3
        return text[:end] + "\n" + note + text[end:]
    return note + "\n" + text


def _is_managed(path: Path) -> bool:
    if path.is_dir():
        path = path / "SKILL.md"
    try:
        return path.is_file() and MARKER in path.read_text(encoding="utf-8", errors="ignore")[:4000]
    except OSError:
        return False


def _write(path: Path, text: str, report: Report, root: Path) -> None:
    rel = path.relative_to(root).as_posix()
    if path.exists() and not _is_managed(path):
        report.kept.append(rel)
        return
    if path.exists() and path.read_text(encoding="utf-8") == text:
        report.unchanged += 1
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")
    report.written.append(rel)


def _agent_text(text: str, name: str) -> str:
    """opencode agents carry the model of their role when that role uses opencode."""
    tool, model = role(name)
    lines = text.splitlines(keepends=True)
    if tool == "opencode" and model:
        return "".join(line.replace("{{model}}", model) for line in lines)
    return "".join(line for line in lines if "{{model}}" not in line)  # the tool's default model


def targets(kind: str, name: str) -> list[Path]:
    if kind == "skills":
        return [Path(".claude/skills") / name / "SKILL.md", Path(".opencode/skill") / name / "SKILL.md",
                Path(".coursekit/agents/skills") / name / "SKILL.md"]
    if kind == "commands":
        return [Path(".claude/commands") / f"{name}.md", Path(".opencode/command") / f"{name}.md",
                Path(".coursekit/agents/commands") / f"{name}.md"]
    if kind == "agents":
        return [Path(".opencode/agent") / f"{name}.md"]
    return [Path(".coursekit/docs") / f"{name}.md"]


GENERATED_DIRS = {
    "skills": [".claude/skills", ".opencode/skill", ".coursekit/agents/skills"],
    "commands": [".claude/commands", ".opencode/command", ".coursekit/agents/commands"],
    "agents": [".opencode/agent"],
    "docs": [".coursekit/docs"],
}


def generate(project: Project) -> Report:
    root = project.root
    values = context(project)
    sources, partials = collect(project)
    report = Report()
    for kind in KINDS:
        for name, source in sources[kind].items():
            path = source / "SKILL.md" if kind == "skills" else source
            package = _package_dir() in path.parents
            origin = (f"to change it, add an override in .agents/{kind}/" if package
                      else f"edit {path.relative_to(root).as_posix()}")
            text = path.read_text(encoding="utf-8")
            if kind == "agents":
                text = _agent_text(text, name)
            text = _mark(render(text, values, partials, path.name), origin)
            for target in targets(kind, name):
                _write(root / target, text, report, root)
            if kind == "skills":  # other files of a skill folder (examples, assets) are copied as they are
                for extra in source.rglob("*"):
                    if extra.is_file() and extra.name not in ("SKILL.md", "__init__.py") and "__pycache__" not in extra.parts:
                        for target in targets(kind, name):
                            dest = root / target.parent / extra.relative_to(source)
                            dest.parent.mkdir(parents=True, exist_ok=True)
                            shutil.copyfile(extra, dest)
        expected = set(sources[kind]) if kind == "skills" else {f"{n}.md" for n in sources[kind]}
        for folder in GENERATED_DIRS[kind]:
            base = root / folder
            if not base.is_dir():
                continue
            for entry in sorted(base.iterdir()):
                if entry.name not in expected and _is_managed(entry):
                    shutil.rmtree(entry) if entry.is_dir() else entry.unlink()
                    report.removed.append(entry.relative_to(root).as_posix())
    report.configs = write_configs(project, values)
    return report


# ── tool configuration ─────────────────────────────────────────────────────────────────────

def _load_json(path: Path) -> dict:
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8") or "{}")
    except json.JSONDecodeError as exc:
        raise RenderError(f"{path.name} is not valid JSON ({exc}); fix it and run `coursekit agents` again") from exc


def _save_json(path: Path, data: dict) -> bool:
    text = json.dumps(data, indent=2, ensure_ascii=False) + "\n"
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")
    return True


def write_configs(project: Project, values: dict[str, str]) -> list[str]:
    root = project.root
    slxd = (config.project_data(project).get("platform") or {}).get("slxd") or {}
    url = str(slxd.get("mcp_url") or "").strip()
    name = values["mcp_name"]
    changed = []

    mcp = _load_json(root / ".mcp.json")
    if url:
        mcp.setdefault("mcpServers", {})[name] = {"type": "http", "url": url}
    if mcp and _save_json(root / ".mcp.json", mcp):
        changed.append(".mcp.json")

    oc = _load_json(root / "opencode.json")
    oc.setdefault("$schema", "https://opencode.ai/config.json")
    instructions = oc.setdefault("instructions", [])
    for item in ("AGENTS.md", ".coursekit/docs/content-format.md"):
        if item not in instructions:
            instructions.append(item)
    if url:
        oc.setdefault("mcp", {})[name] = {"type": "remote", "url": url, "enabled": True}
    bash = oc.setdefault("permission", {}).setdefault("bash", {})
    if isinstance(bash, dict):
        bash.update(DENY_OPENCODE)
    if _save_json(root / "opencode.json", oc):
        changed.append("opencode.json")

    settings = _load_json(root / ".claude" / "settings.json")
    deny = settings.setdefault("permissions", {}).setdefault("deny", [])
    for rule in DENY_CLAUDE:
        if rule not in deny:
            deny.append(rule)
    if _save_json(root / ".claude" / "settings.json", settings):
        changed.append(".claude/settings.json")

    codex = root / ".codex" / "config.toml"
    if url and (not codex.exists() or MARKER in codex.read_text(encoding="utf-8")):
        text = (
            f"# {MARKER} (from project.yaml › platform.slxd). Remove this line to manage the file by hand.\n"
            f"[mcp_servers.{json.dumps(name)}]\nurl = {json.dumps(url)}\n"
        )
        if not codex.exists() or codex.read_text(encoding="utf-8") != text:
            codex.parent.mkdir(parents=True, exist_ok=True)
            codex.write_text(text, encoding="utf-8", newline="\n")
            changed.append(".codex/config.toml")
    return changed
