"""`coursekit catalog`: the tracking Excel built from every courses/*/course.yaml.

Generated output, never edited by hand. Written in the project's ui_language (es | en).
"""

from __future__ import annotations

import datetime as dt
import json
from collections.abc import Callable
from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter

from coursekit import config
from coursekit import course as coursemod
from coursekit.project import Project
from coursekit.util import git, load_yaml
from coursekit.verify import Syntax, learner_words, split_sections

CATALOG_NAME = {"es": "catalogo-cursos.xlsx", "en": "course-catalog.xlsx"}
LINK_FONT = Font(color="0563C1", underline="single")

TEXT = {
    "es": {
        "sheets": ("Cursos", "Unidades", "Información"),
        "course": [("Código", 12), ("Título", 45), ("Estado", 20), ("Horas", 8), ("Unidades", 10),
                   ("Palabras mínimas", 16), ("Palabras actuales", 16), ("% palabras", 11),
                   ("Recursos multimedia", 18), ("Recursos producidos", 18),
                   ("Carpeta", 40),
                   ("DI aprobado por", 26), ("DI aprobado el", 18),
                   ("Resp. DI", 18), ("Resp. redacción", 18), ("Resp. revisión", 18), ("Resp. multimedia", 18),
                   ("Resp. montaje", 18), ("Última actualización", 18), ("Última nota", 40)],
        "unit": [("Código", 12), ("Unidad", 8), ("Título", 45), ("Estado", 14), ("Horas", 8),
                 ("Palabras mínimas", 16), ("Palabras actuales", 16), ("Recursos multimedia", 18),
                 ("Aprobación editorial", 26), ("Aprobada el", 18), ("ID de contenido", 28), ("Enlace compartido", 40), ("Review", 40)],
        "info": ("Generado", "Origen", "Rama / commit", "Generado por", "Aviso"),
        "notice": "Fichero generado: no editar a mano. Los cambios se hacen en el course.yaml de cada curso.",
        "status": {
            "design": "Diseño instruccional (propuesta)", "design_approved": "DI aprobado", "writing": "Redacción",
            "ai_review": "Revisión IA", "editorial_review": "Revisión editorial", "media": "Multimedia",
            "assembly": "Montaje", "client_review": "Review del cliente", "delivered": "Entregado", "on_hold": "En pausa",
        },
    },
    "en": {
        "sheets": ("Courses", "Units", "About"),
        "course": [("Code", 12), ("Title", 45), ("Status", 20), ("Hours", 8), ("Units", 10),
                   ("Minimum words", 16), ("Current words", 16), ("% words", 11),
                   ("Media assets", 18), ("Assets produced", 18),
                   ("Folder", 40),
                   ("Design approved by", 26), ("Design approved on", 18),
                   ("Design lead", 18), ("Writing lead", 18), ("Review lead", 18), ("Media lead", 18),
                   ("Assembly lead", 18), ("Last update", 18), ("Last note", 40)],
        "unit": [("Code", 12), ("Unit", 8), ("Title", 45), ("Status", 14), ("Hours", 8),
                 ("Minimum words", 16), ("Current words", 16), ("Media assets", 18),
                 ("Editorial approval", 26), ("Approved on", 18), ("Content ID", 28), ("Share link", 40), ("Review", 40)],
        "info": ("Generated", "Source", "Branch / commit", "Generated by", "Notice"),
        "notice": "Generated file: do not edit by hand. Changes are made in each course's course.yaml.",
        "status": {
            "design": "Instructional design (proposal)", "design_approved": "Design approved", "writing": "Writing",
            "ai_review": "AI review", "editorial_review": "Editorial review", "media": "Media",
            "assembly": "Assembly", "client_review": "Client review", "delivered": "Delivered", "on_hold": "On hold",
        },
    },
}


def ui_language(project: Project) -> str:
    lang = str(config.project_data(project).get("ui_language") or config.project_data(project).get("content_language") or "es")
    return lang if lang in TEXT else "es"


def file_name(project: Project) -> str:
    return CATALOG_NAME[ui_language(project)]


def header_color(project: Project) -> str:
    """The accent of the project theme (theme/tokens.json), or a neutral dark grey."""
    path = project.theme_dir / "tokens.json"
    if path.exists():
        try:
            colors = json.loads(path.read_text(encoding="utf-8")).get("color") or {}
            value = colors.get("accent-strong") or colors.get("accent")
            if value:
                return value.lstrip("#").upper()
        except ValueError:
            pass
    return "333333"


def unit_stats(course: dict, unit: dict) -> tuple[int, int, int]:
    """(minimum words, current learner words, placeholders) of a unit."""
    min_words = sum(s.get("min_words", 0) for s in unit.get("sections") or [])
    path = coursemod.unit_dir(course["_dir"], unit["n"]) / "content.md"
    if not path.exists():
        return min_words, 0, 0
    syntax = Syntax.for_tokens(coursemod.tokens(course))
    text = path.read_text(encoding="utf-8")
    words = sum(learner_words(s.lines, syntax) for s in split_sections(text, syntax))
    placeholders = sum(1 for line in text.splitlines() if syntax.placeholder.match(line))
    return min_words, words, placeholders


def content_approval(course: dict, n: int) -> dict | None:
    found = [a for a in course.get("approvals") or [] if a.get("gate") == "content" and a.get("unit") == n]
    return found[-1] if found else None


def _sheet(ws, headers, rows, fill: PatternFill, link_columns=()):
    ws.append([h for h, _ in headers])
    for col, (_, width) in enumerate(headers, 1):
        cell = ws.cell(row=1, column=col)
        cell.fill, cell.font = fill, Font(bold=True, color="FFFFFF")
        cell.alignment = Alignment(vertical="center", wrap_text=True)
        ws.column_dimensions[get_column_letter(col)].width = width
    for row in rows:
        ws.append(row)
    for col in link_columns:
        for r in range(2, ws.max_row + 1):
            cell = ws.cell(row=r, column=col)
            if cell.value:
                cell.hyperlink, cell.font = cell.value, LINK_FONT
    ws.freeze_panes = "B2"
    ws.auto_filter.ref = ws.dimensions


def build(project: Project, output: Path, folder_url: Callable[[str], str] | None = None) -> tuple[int, int]:
    """Write the catalog atomically. Returns (courses, units). Raises PermissionError if it is open."""
    text = TEXT[ui_language(project)]
    course_rows, unit_rows = [], []
    for folder in project.iter_courses():
        course = coursemod.load(project, str(folder))
        manifest_path = folder / "media" / "manifest.yaml"
        assets = (load_yaml(manifest_path).get("assets") or []) if manifest_path.exists() else []
        produced = sum(1 for a in assets if a.get("status") in ("produced", "uploaded"))
        total_min = total_words = total_ph = 0
        for unit in course.get("units") or []:
            min_words, words, placeholders = unit_stats(course, unit)
            total_min, total_words, total_ph = total_min + min_words, total_words + words, total_ph + placeholders
            approval = content_approval(course, unit["n"]) or {}
            unit_rows.append([course["code"], unit["n"], unit.get("title"), unit.get("status"), unit.get("hours"),
                              min_words, words, placeholders, approval.get("by"),
                              str(approval.get("at") or "")[:16].replace("T", " "), unit.get("content_id"),
                              (unit.get("links") or {}).get("preview"), (unit.get("links") or {}).get("review")])
        last = (course.get("history") or [{}])[-1]
        owners = course.get("owners") or {}
        design = coursemod.design_approval(course) or {}
        course_rows.append([
            course["code"], course.get("title"), text["status"].get(course.get("status"), course.get("status")),
            course["design"].get("hours"), len(course.get("units") or []),
            total_min, total_words, round(total_words / total_min, 3) if total_min else 0,
            max(total_ph, len(assets)), produced,
            folder_url(course["code"]) if folder_url else None,
            design.get("by"), str(design.get("at") or "")[:16].replace("T", " "),
            owners.get("instructional_design"), owners.get("writing"), owners.get("review"),
            owners.get("media"), owners.get("assembly"), str(last.get("date", "")), last.get("note"),
        ])

    fill = PatternFill("solid", fgColor=header_color(project))
    wb = Workbook()
    ws = wb.active
    ws.title = text["sheets"][0]
    _sheet(ws, text["course"], course_rows, fill, link_columns=(11,))
    for r in range(2, ws.max_row + 1):
        ws.cell(row=r, column=8).number_format = "0%"
        for c in (6, 7):
            ws.cell(row=r, column=c).number_format = "#,##0"
    _sheet(wb.create_sheet(text["sheets"][1]), text["unit"], unit_rows, fill, link_columns=(12, 13))
    info = wb.create_sheet(text["sheets"][2])
    labels = text["info"]
    info.append([labels[0], dt.datetime.now().strftime("%Y-%m-%d %H:%M")])
    info.append([labels[1], "courses/*/course.yaml (coursekit catalog)"])
    revision = git("branch", "--show-current", cwd=project.root) + " · " + git("rev-parse", "--short", "HEAD", cwd=project.root)
    info.append([labels[2], revision])
    info.append([labels[3], git("config", "user.name", cwd=project.root)])
    info.append([labels[4], text["notice"]])
    info.column_dimensions["A"].width, info.column_dimensions["B"].width = 16, 90

    output.parent.mkdir(parents=True, exist_ok=True)
    tmp = output.with_name(f".~{output.name}")
    wb.save(tmp)
    try:
        tmp.replace(output)
    except PermissionError:
        tmp.unlink(missing_ok=True)
        raise
    return len(course_rows), len(unit_rows)
